### ISSUE TITLE
Feature Request: Color Status Bar on Android Chrome

### ISSUE THREAD

**Issue by jacobertel** [caleb531/intervarsity-theme#1]
Caleb, thank you for all of your hard work! It is appreciated greatly!

Android recently allowed the status bar color of the phone to be set by websites. Just paste this in the header and customize with the appropriate color.
 `
<meta name="theme-color" content="#4285f4">`

See [here](https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/theme-color?hl=en) for more details

**Comment by caleb531** [comment]
I think that's a great idea, especially since I could use the user-set theme accent color for this. Thanks for the suggestion; I will add it very soon. :)

**Comment by caleb531** [comment]
Alright, changes pushed! Please download the latest revision of the theme from [branch `develop`](https://github.com/caleb531/intervarsity-theme/tree/develop) and let me know if the color detection works for you. Please send me a screenshot if possible; I'd like to assess how visually appealing/worthwhile the difference is (in case a different, static color might be better suited).

**Comment by jacobertel** [comment]
![screenshot_20160407-122417](https://cloud.githubusercontent.com/assets/3068646/14360457/1f80e804-fcbc-11e5-8c0a-59e199fc4e01.png)

Thanks Caleb. That was fast. I am trying to work with official InterVarsity colors. Hence the dark blue background and gold accent colors.

**Comment by caleb531** [comment]
Hmm, looks pretty decent, actually. I think I'll keep this, then. Thanks again for the suggestion.
