### ISSUE TITLE
Feature Request: Blog Roll on Home Page

### ISSUE THREAD

**Issue by jacobertel** [caleb531/intervarsity-theme#3]
Is there a way to put a blog roll below the static home page? I am hoping to have the home page include a slider, your custom content boxes, and then the blog roll with the latest blog posts.

I am a student at MSOE. My chapter sends out weekly emails, and I am hoping to have the weeks blog mirror the email.

Thanks again for all of your hard work.

**Comment by caleb531** [comment]
That's actually a brilliant idea. I will begin working on the feature as soon as I can. :)

**Comment by caleb531** [comment]
Alright, I just pushed a commit to [`branch develop`](https://github.com/caleb531/intervarsity-theme/tree/develop) with a new Customizer setting which can be found as **Front Page > General > Posts to show**. If set to a number greater than zero, that many recent blog posts will show under all front page content (sliders, content boxes, and all).

@jacobertel, please download the latest build and let me know if this setting is sufficient for your needs. :)

**Comment by jacobertel** [comment]
Thanks Caleb!

**Comment by caleb531** [comment]
My pleasure! As always, let me know if there's anything else you'd like me to add! :)

I hope to officially release the next minor version of the theme (v2.3.0) later this week.

Caleb
