### ISSUE TITLE
Front Page Image Link

### ISSUE THREAD

**Issue by jacobertel** [caleb531/intervarsity-theme#4]
Caleb, How did you link to a page from the featured photo on the home page of ivnorthcounty.org?

**Comment by caleb531** [comment]
I used the [Cyclone Slider 2](https://wordpress.org/plugins/cyclone-slider-2/) plugin—which the InterVarsity theme integrates with—to set a Featured Slider on the front page.

To do so:
1. Install Cyclone Slider 2
2. Create a new slider under the Cyclone Slider section of WordPress Admin
3. Set the front page's Featured Slider to the slider you just created.

Let me know if you have any questions. :)
Caleb

**Comment by jacobertel** [comment]
Duh! (facepalm) Thanks Caleb :)
