### ISSUE TITLE
Bug: Cyclone Slider 2 loads but disapears

### ISSUE THREAD

**Issue by jacobertel** [caleb531/intervarsity-theme#5]
Hi Caleb,
On the homepage of my installs, the slider will load, but disappear. This happens on Chrome (desktop and Android), but not on IE 11.

msoeiv.org is running the latest master commit.
demo1.jacobertel.com is running develop branch commit f013906 "Add setting for number of posts to show on front page"

**Comment by caleb531** [comment]
Oh, I think I know what's going on.

Try setting the template for that slider to "Standard". That was the template I chose for the sliders on the IV North County website, and I really only designed the theme for that particular slider template (I disabled the others in the Cyclone Slider 2 settings).

For now, I can update the documentation indicating that "Standard" is the only supported slider template. In the future, I _may_ add support for the other templates, but it'd be more work than I have the time for at this time.
